// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace eVideoPrime.DAL.Entities
{
    public partial class Subscription
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public DateTime SubscribedOn { get; set; }
        public DateTime ExpiryOn { get; set; }
        public int PlanId { get; set; }
        [NotMapped]
        public string UserName { get; set; }
        [NotMapped]
        public string PlanName { get; set; }
        
    }
}